version: '3'
services:
  database:
    container_name: database
    image: 'postgres:14'
    ports:
      - 5434:5434
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=nginx
    volumes:
      - nps_data:/var/lib/postgresql/data
    restart: always
  server:
    container_name: server
    image: kondrashev/nginx_server:latest
    restart: always
    environment:
      - DB_NAME=nginx
      - DB_USER=postgres
      - DB_PASSWORD=1234
      - DB_HOST=database
    ports:
      - 3000:3000
    links:
      - database
  client:
    container_name: client
    image: kondrashev/nginx_client:latest
    restart: always
    environment:
      API_BASE_URL: server
    links:
      - server
  nginx:
    container_name: nginx
    depends_on:
      - server
      - client
    image: nginx:latest
    volumes:
      - ./:/etc/nginx/conf.d/:ro
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    ports:
      - 80:80
      - 443:443
  certbot:
    image: certbot/certbot:latest
    depends_on:
      - nginx
    container_name: certbot
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
volumes:
  nps_data: {}
