version: '3'
services:
  database:
    container_name: database
    image: 'postgres:14'
    ports:
      - 5434:5434
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=nginx
    volumes:
      - nps_data:/var/lib/postgresql/data
    restart: always
    networks:
      - app
  server:
    container_name: server
    platform: linux/amd64
    build:
      context: ./server
    restart: always
    environment:
      - DB_NAME=nginx
      - DB_USER=postgres
      - DB_PASSWORD=1234
      - DB_HOST=database
    ports:
      - 3000:3000
    links:
      - database
    volumes:
      - /app/node_modules
      - ./server:/app
    networks:
      - app
  client:
    container_name: client
    platform: linux/amd64
    build:
      context: ./client
    restart: always
    links:
      - server
    volumes:
      - /app/node_modules
      - ./client:/app
    networks:
      - app
  nginx:
    container_name: nginx
    depends_on:
      - server
      - client
    image: nginx:latest
    volumes:
      - ./:/etc/nginx/conf.d/:ro
      - ./client/dist:/dist/:rw
    ports:
      - 80:80
    networks:
      - app
volumes:
  nps_data: {}
networks:
  app:
    driver: bridge
