version: '3'
services:
  database:
    container_name: database
    image: 'postgres:14'
    ports:
      - 5434:5434
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=nginx
    volumes:
      - nps_data:/var/lib/postgresql/data
    restart: always
    networks:
      - app
  server:
    container_name: server
    image: kondrashev/nginx_server:latest
    restart: always
    environment:
      - DB_NAME=nginx
      - DB_USER=postgres
      - DB_PASSWORD=1234
      - DB_HOST=database
    ports:
      - 3000:3000
    links:
      - database
    networks:
      - app
  client:
    container_name: client
    image: kondrashev/nginx_client:latest
    restart: always
    links:
      - server
    networks:
      - app
  nginx:
    container_name: nginx
    depends_on:
      - server
      - client
    image: nginx:latest
    volumes:
      - ./:/etc/nginx/conf.d/:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /tmp/acme_challenge:/tmp/acme_challenge
    ports:
      - 80:80
      - 443:443
    networks:
      - app
volumes:
  nps_data: {}
networks:
  app:
    driver: bridge
